### ISSUE TITLE
Checkpoint restoration

### ISSUE THREAD

**Issue by nikwalia** [jacobkrantz/VLN-CE#23]
Hello,
Thank you so much for putting together this dataset and codebase! I am trying to reproduce your results; however, I am unable to find any references to restore training from checkpoints. I am using the default config provided. Some pointers would be much appreciated!

Thank you very much!

**Comment by jacobkrantz** [comment]
Hi @nikwalia, thank you for your interest! I'll answer this from the perspective of the [rxr-habitat-challenge](/jacobkrantz/VLN-CE/tree/rxr-habitat-challenge) branch. 

If using the `RecollectTrainer`, each checkpoint saves the current training epoch and step_id. To continue training from a given checkpoint, set these additional entries in your config:
```yaml
IL:
  ckpt_to_load: /path/to/checkpoint.pth
  is_requeue: True
  load_from_ckpt: True
```

Then when you start training again, `_initialize_policy()` should automatically restore the model, optimizer, and training steps. You can compare training losses to ensure the checkpoint was restored properly. 

Restoring checkpoints is currently unsupported in the `DaggerTrainer`. Edge cases relating to the online dataset collected during training would need to be addressed. If doing teacher forcing, a precomputed dataset can be used to skip straight to model training:
```yaml
IL:
  DAGGER:
    preload_lmdb_features: True
    lmdb_features_dir: /path/to/dataset
```
